In [39]:
import pandas as pd
import csv
import json

import importlib
# import notebooks.clean_templates_util as clean_templates_util
import clean_templates_util
importlib.reload(clean_templates_util)
from clean_templates_util import is_ignored_template, ReducedTemplate, \
reconstruct_template, process_recursive_templates, _pd_obtain_filtered_templates, match_templates, \
insert_expansions, to_textual_unnested, insert_expansions_custom
# insert_wikicode

In [5]:
df = pd.read_csv('etytree_large_joined_clean_v2.csv')

In [6]:
import ast

stdf = df['templates'].apply(ast.literal_eval)
df['templates'] = stdf

In [7]:
df['filtered'] = df.apply(lambda x: _pd_obtain_filtered_templates(x['ety_text'], x['templates']), axis=1)
df

,word,language,ety_number,ety,ety_text,templates,num_templates,filtered
0,dictionary,English,0,"From Middle English dixionare, learned borrowi...",{{root|en|ine-pro|*deyḱ-}} From {{inh|en|enm|d...,"[{'name': 'root', 'args': {'1': 'en', '2': 'in...",10,"[{'name': 'root', 'args': {'1': 'en', '2': 'in..."
1,pound,English,1,"From Middle English pound, from Old English pu...",{{root|en|ine-pro|*(s)pend-}} From {{inh|en|en...,"[{'name': 'root', 'args': {'1': 'en', '2': 'in...",13,"[{'name': 'root', 'args': {'1': 'en', '2': 'in..."
2,pie,English,1,"From Middle English pye, pie, pey, perhaps fro...","From {{inh|en|enm|pye}}, {{m|enm|pie}}, {{m|en...","[{'name': 'inh', 'args': {'1': 'en', '2': 'enm...",14,"[{'name': 'inh', 'args': {'1': 'en', '2': 'enm..."
3,pie,Spanish,1,"Inherited from Old Spanish pie, from Latin ped...",{{dercat|es|itc-pro|ine-pro|inh=2}} {{inh+|es|...,"[{'name': 'dercat', 'args': {'1': 'es', '2': '...",10,"[{'name': 'dercat', 'args': {'1': 'es', '2': '..."
4,A,English,1,From Middle English and Old English upper case...,From {{der|en|enm|-}} and {{der|en|ang|-}} upp...,"[{'name': 'der', 'args': {'1': 'en', '2': 'enm...",12,"[{'name': 'der', 'args': {'1': 'en', '2': 'enm..."
...,...,...,...,...,...,...,...,...
20671,teich,Scottish Gaelic,0,"From Old Irish teichid (Irish teith, Manx çhea...",{{root|gd|ine-pro|*tekʷ-}} From {{inh|gd|sga|t...,"[{'name': 'root', 'args': {'1': 'gd', '2': 'in...",11,"[{'name': 'root', 'args': {'1': 'gd', '2': 'in..."
20672,পদ,Bengali,0,"Inherited from Sanskrit পদ (pada, “step, foot,...","{{inh+|bn|sa|पद|পদ |step, foot, position}}, fr...","[{'name': 'glossary', 'args': {'1': 'Inherited...",14,"[{'name': 'inh+', 'args': {'1': 'bn', '2': 'sa..."
20673,নীতি,Bengali,0,Borrowed from Sanskrit নীতি (nīti). Cognate wi...,{{bor+|bn|sa|नीति|নীতি}}. Cognate with {{cog|a...,"[{'name': 'glossary', 'args': {'1': 'loanword'...",10,"[{'name': 'bor+', 'args': {'1': 'bn', '2': 'sa..."
20674,জগৎ,Bengali,0,Borrowed from Sanskrit জগৎ (jagat). Cognate wi...,{{bor+|bn|sa|जगत्|জগৎ}}. Cognate with {{cog|as...,"[{'name': 'glossary', 'args': {'1': 'loanword'...",10,"[{'name': 'bor+', 'args': {'1': 'bn', '2': 'sa..."
20675,বহু,Bengali,1,Borrowed from Sanskrit বহু (bahu). Compare Ass...,{{bor+|bn|sa|बहु|বহু}}. Compare {{cog|as|বহু}}...,"[{'name': 'glossary', 'args': {'1': 'loanword'...",11,"[{'name': 'bor+', 'args': {'1': 'bn', '2': 'sa..."

In [8]:
df['matched'] = df.apply(lambda x: match_templates(x['ety_text'], x['templates']), axis=1)
df

,word,language,ety_number,ety,ety_text,templates,num_templates,filtered,matched
0,dictionary,English,0,"From Middle English dixionare, learned borrowi...",{{root|en|ine-pro|*deyḱ-}} From {{inh|en|enm|d...,"[{'name': 'root', 'args': {'1': 'en', '2': 'in...",10,"[{'name': 'root', 'args': {'1': 'en', '2': 'in...","[{{root|en|ine-pro|*deyḱ-}}, {{inh|en|enm|dixi..."
1,pound,English,1,"From Middle English pound, from Old English pu...",{{root|en|ine-pro|*(s)pend-}} From {{inh|en|en...,"[{'name': 'root', 'args': {'1': 'en', '2': 'in...",13,"[{'name': 'root', 'args': {'1': 'en', '2': 'in...","[{{root|en|ine-pro|*(s)pend-}}, {{inh|en|enm|p..."
2,pie,English,1,"From Middle English pye, pie, pey, perhaps fro...","From {{inh|en|enm|pye}}, {{m|enm|pie}}, {{m|en...","[{'name': 'inh', 'args': {'1': 'en', '2': 'enm...",14,"[{'name': 'inh', 'args': {'1': 'en', '2': 'enm...","[{{inh|en|enm|pye}}, {{m|enm|pie}}, {{m|enm|pe..."
3,pie,Spanish,1,"Inherited from Old Spanish pie, from Latin ped...",{{dercat|es|itc-pro|ine-pro|inh=2}} {{inh+|es|...,"[{'name': 'dercat', 'args': {'1': 'es', '2': '...",10,"[{'name': 'dercat', 'args': {'1': 'es', '2': '...","[{{dercat|es|itc-pro|ine-pro|inh=2}}, {{inh+|e..."
4,A,English,1,From Middle English and Old English upper case...,From {{der|en|enm|-}} and {{der|en|ang|-}} upp...,"[{'name': 'der', 'args': {'1': 'en', '2': 'enm...",12,"[{'name': 'der', 'args': {'1': 'en', '2': 'enm...","[{{der|en|enm|-}}, {{der|en|ang|-}}, {{m|enm|A..."
...,...,...,...,...,...,...,...,...,...
20671,teich,Scottish Gaelic,0,"From Old Irish teichid (Irish teith, Manx çhea...",{{root|gd|ine-pro|*tekʷ-}} From {{inh|gd|sga|t...,"[{'name': 'root', 'args': {'1': 'gd', '2': 'in...",11,"[{'name': 'root', 'args': {'1': 'gd', '2': 'in...","[{{root|gd|ine-pro|*tekʷ-}}, {{inh|gd|sga|teic..."
20672,পদ,Bengali,0,"Inherited from Sanskrit পদ (pada, “step, foot,...","{{inh+|bn|sa|पद|পদ |step, foot, position}}, fr...","[{'name': 'glossary', 'args': {'1': 'Inherited...",14,"[{'name': 'inh+', 'args': {'1': 'bn', '2': 'sa...","[{{inh+|bn|sa|पद|পদ|step, foot, position}}, {{..."
20673,নীতি,Bengali,0,Borrowed from Sanskrit নীতি (nīti). Cognate wi...,{{bor+|bn|sa|नीति|নীতি}}. Cognate with {{cog|a...,"[{'name': 'glossary', 'args': {'1': 'loanword'...",10,"[{'name': 'bor+', 'args': {'1': 'bn', '2': 'sa...","[{{bor+|bn|sa|नीति|নীতি}}, {{cog|as|নীতি}}, {{..."
20674,জগৎ,Bengali,0,Borrowed from Sanskrit জগৎ (jagat). Cognate wi...,{{bor+|bn|sa|जगत्|জগৎ}}. Cognate with {{cog|as...,"[{'name': 'glossary', 'args': {'1': 'loanword'...",10,"[{'name': 'bor+', 'args': {'1': 'bn', '2': 'sa...","[{{bor+|bn|sa|जगत्|জগৎ}}, {{cog|as|জগৎ}}, {{co..."
20675,বহু,Bengali,1,Borrowed from Sanskrit বহু (bahu). Compare Ass...,{{bor+|bn|sa|बहु|বহু}}. Compare {{cog|as|বহু}}...,"[{'name': 'glossary', 'args': {'1': 'loanword'...",11,"[{'name': 'bor+', 'args': {'1': 'bn', '2': 'sa...","[{{bor+|bn|sa|बहु|বহু}}, {{cog|as|বহু}}, {{cog..."

In [9]:
fine = df.dropna(subset=['filtered'])

In [10]:
# find df \ nully
nully = df[~df.index.isin(fine.index)]

In [11]:
nully

Empty DataFrame
Columns: [word, language, ety_number, ety, ety_text, templates, num_templates, filtered, matched]
Index: []

In [55]:
# save fine to a pickle
fine.to_pickle('fine.pkl')

In [39]:
# load fine from a pickle
fine = pd.read_pickle('fine.pkl')

In [41]:
insert_expansions_custom(df.loc[0, "ety_text"], df.loc[0, "matched"])

' From Middle English dixionare [inherited], learned borrowing from Medieval Latin dictiōnārium [derived], from Latin dictiōnārius [derived], from dictiō (“speaking”) [mention], from dictus [mention], perfect past participle of dīcō (“speak”) [mention] + -ārium (“room, place”) [mention]. By surface analysis, diction + -ary [surf]. '

In [57]:
import re
# get all nested examples, which we can find by the regex {{[^}]*{{
_is_nested_re = re.compile(r"{{[^}]*{{")
def _is_nested(wikitext):
    return _is_nested_re.search(wikitext) is not None
nested = fine[fine['ety_text'].apply(_is_nested)]

In [58]:
nested.to_pickle('nested.pkl')

In [59]:
unnested = fine[fine['ety_text'].apply(lambda x: not _is_nested(x))]

In [60]:
unnested.to_pickle('unnested.pkl')

In [15]:
to_textual_unnested(unnested.loc[0, "ety_text"], unnested.loc[0, "matched"], lambda x, i: f"{x.original_dict['expansion']}{{{{{x.name}|node{i}}}}}")
# not very good, because often you need to know the language of the template, which is not always given.

NameError: name 'unnested' is not defined

In [81]:
def _simple_expansion(x: ReducedTemplate, i):
    expansion = x.original_dict['expansion']
    if not expansion:
        return ""
    if x.name == "glossary":
        return expansion # glossary: still need to expand, but not a template
    orig_templ_str = x.original_wikitext
    # templ_str = '{{' + orig_templ_str.replace(x.name, f"{x.name}|node{i}", 1) + '}}'
    templ_str = '{{' + f'node{i}|' + orig_templ_str + '}}'
    return f"{x.original_dict['expansion']}{templ_str}"
# to_textual_unnested(unnested.loc[0, "ety_text"], unnested.loc[0, "matched"], _simple_expansion)

def _simple_expand_index(i):
    return unnested.loc[0, "word"] + '{{node' + f'{i}' + '}}\n' \
        + to_textual_unnested(unnested.loc[0, "ety_text"], unnested.loc[0, "matched"], _simple_expansion)


_simple_expand_index(0)

'dictionary{{node0}}\n From Middle English dixionare{{node2|inh|en|enm|dixionare}}, learned borrowing from Medieval Latin dictiōnārium{{node4|der|en|ML.|dictiōnārium}}, from Latin dictiōnārius{{node5|der|en|la|dictiōnārius}}, from dictiō (“speaking”){{node6|m|la|dictiō||a speaking}}, from dictus{{node7|m|la|dictus}}, perfect past participle of dīcō (“speak”){{node8|m|la|dīcō|t= to speak}} + -ārium (“room, place”){{node9|m|la|-ārium|t=room, place}}. By surface analysis, diction + -ary{{node10|surf|en|diction|-ary}}. '