In [1]:
import pandas as pd

In [18]:
df = pd.read_csv('../wikitexts.csv')

C:\Users\conjunct\AppData\Local\Temp\ipykernel_21128\3781191311.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../wikitexts.csv')

In [34]:
df = df.drop_duplicates()

In [35]:
df

,word,language,ety_number,ety_text
0,dictionary,English,0,{{root|en|ine-pro|*deyḱ-}} From {{inh|en|enm|d...
1,free,English,0,{{root|en|ine-pro|*preyH-}} From {{inh|en|enm|...
2,free,Low German,0,"From {{inh|nds|gml|vrîe}}, variant of {{m|gml|..."
3,thesaurus,English,0,"16th century, from {{bor|en|la|thēsaurus}}, fr..."
4,encyclopedia,English,0,{{root|en|ine-pro|*peh₂w-}} From {{bor|en|NL.|...
...,...,...,...,...
725433,निस्तब्ध,Hindi,0,{{root|hi|sa|स्तभ्}} {{root|hi|ine-pro|*stebʰ-...
725434,निस्तब्धता,Hindi,0,{{root|hi|sa|स्तभ्}} {{root|hi|ine-pro|*stebʰ-...
725435,Конфуцій,Ukrainian,0,"{{bor+|uk|la|Cōnfūcius}}, from {{der|uk|cmn|-}..."
725436,ठाढ़ा,Hindi,0,{{root|hi|sa|स्तभ्}} {{root|hi|ine-pro|*stebʰ-...
725437,υπηρετώ,Greek,0,{{lbor|el|grc|ὑπηρετῶ}} with {{sl|el|fr|servir...

In [5]:
templs = pd.read_csv('../ety_data.csv')

In [40]:
print("Before: ", len(templs))
# drop Unnamed: 0
templs = templs.drop(columns=['Unnamed: 0'])
templs = templs.drop_duplicates()
print("After: ", len(templs))

Before:  915351
After:  850735

In [50]:
large = templs[10 <= templs['num_templates']]
large = large[large['num_templates'] <= 15]

In [51]:
large

,word,lang,ety,templates,etymology_number,num_templates,split,subpart
0,abaft,English,"From a- (“on”) + Middle English baft, baften, ...","[{'name': 'm', 'args': {'1': 'en', '2': 'a-', ...",0,10,-1,1
2,abraid,English,"From Middle English abraiden, abreiden (“to st...","[{'name': 'inh', 'args': {'1': 'en', '2': 'enm...",1,10,-1,1
3,abear,English,"From Middle English aberen, from Old English ā...","[{'name': 'inh', 'args': {'1': 'en', '2': 'enm...",0,10,-1,1
5,ablative,English,"From Middle English ablative, ablatife, ablaty...","[{'name': 'inh', 'args': {'1': 'en', '2': 'enm...",0,10,-1,1
7,abduction,English,"From Latin abductiō (“robbing; abduction”), fr...","[{'name': 'root', 'args': {'1': 'en', '2': 'in...",0,10,-1,1
...,...,...,...,...,...,...,...,...
26175,толмач,Macedonian,"Inherited from Proto-Slavic *tъlmačь, from Pro...","[{'name': 'glossary', 'args': {'1': 'Inherited...",0,15,-1,985
26176,толмач,Russian,"Inherited from Proto-Slavic *tъlmačь, from Pro...","[{'name': 'glossary', 'args': {'1': 'Inherited...",0,15,-1,985
26177,נאָמען,Yiddish,"From Middle High German name, from Old High Ge...","[{'name': 'inh', 'args': {'1': 'yi', '2': 'gmh...",0,15,-1,989
26178,笑,Chinese,Originally ideogrammic compound (會意／会意) or pho...,"[{'name': 'm', 'args': {'1': 'zh', '2': '會意', ...",0,15,-1,99
26179,Donau,German,Attested in this form at least since 1544. Fro...,"[{'name': 'm', 'args': {'1': 'de', '2': 'Donaw...",0,15,-1,998

In [53]:
large.rename(columns={'lang':'language', 'etymology_number': 'ety_number'}, inplace=True)
# drop split and subpart
large = large.drop(columns=['split', 'subpart'])

In [55]:
# filter all rows of df that are stringy in the ety_number column
df_weird = df[~df['ety_number'].apply(lambda x: isinstance(x, int) or isinstance(x, float) or x.isnumeric())]

Empty DataFrame
Columns: [word, language, ety_number, ety_text]
Index: []

In [17]:
df_weird

,word,language,ety_number,ety_text
72801,Wiktionary:Etymology,General,jargon,Some words have conventional usage in etymolog...
72806,Wiktionary:Etymology,Templates,language templates,There are several templates commonly used for ...
147410,Wiktionary:About Ancient Greek,General information,language codes,Ancient Greek has several etymology language c...
167415,Template:ko-basic,Korean,{{{num|2}}},{{{etym|}}} {{</includeonly><includeonly>sub...
192676,Wiktionary:About Hungarian,Hungarian in non-Hungarian entries,of non-Hungarian words,Some words in English and other languages deri...
235773,Wiktionary:About Welsh,Welsh in non-Welsh entries,of non-Welsh words,Some words in English (and other languages) d...
335008,Citations:hatcheck,NaN,2: variant of ''{{l|en|háček}}'',"* '''1981''', [[w:Dell Hymes|Dell H. Hymes]],..."
350249,Citations:hip,NaN,3 Verb,* {{quote-book|en|title=w:The Subterraneans|pa...
449233,Wiktionary:Beer parlour/2017/October,Coptic standardisation,of Copto-Greek verbs,There are three ways in which Coptic dialects ...
513726,Template:ja-see/documentation,Japanese,x,{{ja-kanjitab|かえる|yomi=k}} {{ja-see|蛙}} </pre>
517073,Wiktionary:About Sranan Tongo,Templates,sections,''(Prior discussion on this topic can be found...
682615,કોટ,Gujarati,1===,"{{inh+|gu|pra-sau|𑀓𑁄𑀝𑁆𑀝}}, from {{der|gu|sa|को..."

In [21]:
# set type of etymology number to 0 if not present for df
# if the row cannot be coerced, drop the row
df['ety_number'] = df['ety_number'].fillna(0)
df['ety_number'] = pd.to_numeric(df['ety_number'], errors='coerce')
df = df.dropna(subset=['ety_number'])
df['ety_number'] = df['ety_number'].astype(int)

In [56]:
# add "ety" and "templates" fields to df using a merge
merged_df = df.merge(large, on=['word', 'language', 'ety_number'], how='inner')

In [59]:
merged_df

,word,language,ety_number,ety_text,ety,templates,num_templates
0,dictionary,English,0,{{root|en|ine-pro|*deyḱ-}} From {{inh|en|enm|d...,"From Middle English dixionare, learned borrowi...","[{'name': 'root', 'args': {'1': 'en', '2': 'in...",10
1,pound,English,1,{{root|en|ine-pro|*(s)pend-}} From {{inh|en|en...,"From Middle English pound, from Old English pu...","[{'name': 'root', 'args': {'1': 'en', '2': 'in...",13
2,pie,English,1,"From {{inh|en|enm|pye}}, {{m|enm|pie}}, {{m|en...","From Middle English pye, pie, pey, perhaps fro...","[{'name': 'inh', 'args': {'1': 'en', '2': 'enm...",14
3,pie,Spanish,1,{{dercat|es|itc-pro|ine-pro|inh=2}} {{inh+|es|...,"Inherited from Old Spanish pie, from Latin ped...","[{'name': 'dercat', 'args': {'1': 'es', '2': '...",10
4,A,English,1,From {{der|en|enm|-}} and {{der|en|ang|-}} upp...,From Middle English and Old English upper case...,"[{'name': 'der', 'args': {'1': 'en', '2': 'enm...",12
...,...,...,...,...,...,...,...
21373,teich,Scottish Gaelic,0,{{root|gd|ine-pro|*tekʷ-}} From {{inh|gd|sga|t...,"From Old Irish teichid (Irish teith, Manx çhea...","[{'name': 'root', 'args': {'1': 'gd', '2': 'in...",11
21374,পদ,Bengali,0,"{{inh+|bn|sa|पद|পদ |step, foot, position}}, fr...","Inherited from Sanskrit পদ (pada, “step, foot,...","[{'name': 'glossary', 'args': {'1': 'Inherited...",14
21375,নীতি,Bengali,0,{{bor+|bn|sa|नीति|নীতি}}. Cognate with {{cog|a...,Borrowed from Sanskrit নীতি (nīti). Cognate wi...,"[{'name': 'glossary', 'args': {'1': 'loanword'...",10
21376,জগৎ,Bengali,0,{{bor+|bn|sa|जगत्|জগৎ}}. Cognate with {{cog|as...,Borrowed from Sanskrit জগৎ (jagat). Cognate wi...,"[{'name': 'glossary', 'args': {'1': 'loanword'...",10
21377,বহু,Bengali,1,{{bor+|bn|sa|बहु|বহু}}. Compare {{cog|as|বহু}}...,Borrowed from Sanskrit বহু (bahu). Compare Ass...,"[{'name': 'glossary', 'args': {'1': 'loanword'...",11

In [60]:
# only keep word	language	ety_number	ety_text    templates
df_export = merged_df[['word', 'language', 'ety_number', 'ety', 'ety_text', 'templates', 'num_templates']]

# drop duplicates
df_export = df_export.drop_duplicates()

In [61]:
df_export

,word,language,ety_number,ety,ety_text,templates,num_templates
0,dictionary,English,0,"From Middle English dixionare, learned borrowi...",{{root|en|ine-pro|*deyḱ-}} From {{inh|en|enm|d...,"[{'name': 'root', 'args': {'1': 'en', '2': 'in...",10
1,pound,English,1,"From Middle English pound, from Old English pu...",{{root|en|ine-pro|*(s)pend-}} From {{inh|en|en...,"[{'name': 'root', 'args': {'1': 'en', '2': 'in...",13
2,pie,English,1,"From Middle English pye, pie, pey, perhaps fro...","From {{inh|en|enm|pye}}, {{m|enm|pie}}, {{m|en...","[{'name': 'inh', 'args': {'1': 'en', '2': 'enm...",14
3,pie,Spanish,1,"Inherited from Old Spanish pie, from Latin ped...",{{dercat|es|itc-pro|ine-pro|inh=2}} {{inh+|es|...,"[{'name': 'dercat', 'args': {'1': 'es', '2': '...",10
4,A,English,1,From Middle English and Old English upper case...,From {{der|en|enm|-}} and {{der|en|ang|-}} upp...,"[{'name': 'der', 'args': {'1': 'en', '2': 'enm...",12
...,...,...,...,...,...,...,...
21373,teich,Scottish Gaelic,0,"From Old Irish teichid (Irish teith, Manx çhea...",{{root|gd|ine-pro|*tekʷ-}} From {{inh|gd|sga|t...,"[{'name': 'root', 'args': {'1': 'gd', '2': 'in...",11
21374,পদ,Bengali,0,"Inherited from Sanskrit পদ (pada, “step, foot,...","{{inh+|bn|sa|पद|পদ |step, foot, position}}, fr...","[{'name': 'glossary', 'args': {'1': 'Inherited...",14
21375,নীতি,Bengali,0,Borrowed from Sanskrit নীতি (nīti). Cognate wi...,{{bor+|bn|sa|नीति|নীতি}}. Cognate with {{cog|a...,"[{'name': 'glossary', 'args': {'1': 'loanword'...",10
21376,জগৎ,Bengali,0,Borrowed from Sanskrit জগৎ (jagat). Cognate wi...,{{bor+|bn|sa|जगत्|জগৎ}}. Cognate with {{cog|as...,"[{'name': 'glossary', 'args': {'1': 'loanword'...",10
21377,বহু,Bengali,1,Borrowed from Sanskrit বহু (bahu). Compare Ass...,{{bor+|bn|sa|बहु|বহু}}. Compare {{cog|as|বহু}}...,"[{'name': 'glossary', 'args': {'1': 'loanword'...",11

In [62]:
# write df_export
df_export.to_csv('etytree_large_joined.csv', index=False)

In [58]:
df_export

,word,language,ety_number,ety,ety_text,templates
0,dictionary,English,0,"From Middle English dixionare, learned borrowi...",{{root|en|ine-pro|*deyḱ-}} From {{inh|en|enm|d...,"[{'name': 'root', 'args': {'1': 'en', '2': 'in..."
2,pie,Spanish,1,"Inherited from Old Spanish pie, from Latin ped...",{{dercat|es|itc-pro|ine-pro|inh=2}} {{inh+|es|...,"[{'name': 'dercat', 'args': {'1': 'es', '2': '..."
3,march,English,3,"From Middle English merche, from Old English m...","From {{inh|en|enm|merche}}, from {{inh|en|ang|...","[{'name': 'inh', 'args': {'1': 'en', '2': 'enm..."
4,June,English,1,"From Middle English June, june, re-Latinised v...","From {{inh|en|enm|June}}, {{m|enm|june}}, re-L...","[{'name': 'inh', 'args': {'1': 'en', '2': 'enm..."
5,trade,Galician,1,"From Old Galician-Portuguese traado, independe...","From {{inh|gl|roa-opt|traado}}, independently ...","[{'name': 'inh', 'args': {'1': 'gl', '2': 'roa..."
...,...,...,...,...,...,...
7780,જાવું,Gujarati,0,"Inherited from Old Gujarati जाइ (jāi), from Pr...","{{inh+|gu|inc-ogu|जाइ}}, from {{inh|gu|inc-pra...","[{'name': 'glossary', 'args': {'1': 'Inherited..."
7781,abugaw,Tausug,0,"Borrowed from Asturian abogáu (“lawyer”), Inhe...",{{bor+|tsg|ast|abogáu||lawyer}} from {{der|tsg...,"[{'name': 'glossary', 'args': {'1': 'loanword'..."
7782,ব্যাপার,Bengali,0,Borrowed from Sanskrit ৱ্যাপার (vyāpāra). Cogn...,{{bor+|bn|sa|व्यापार|ৱ্যাপার}}. Cognate with {...,"[{'name': 'glossary', 'args': {'1': 'loanword'..."
7783,নীতি,Bengali,0,Borrowed from Sanskrit নীতি (nīti). Cognate wi...,{{bor+|bn|sa|नीति|নীতি}}. Cognate with {{cog|a...,"[{'name': 'glossary', 'args': {'1': 'loanword'..."
7784,জগৎ,Bengali,0,Borrowed from Sanskrit জগৎ (jagat). Cognate wi...,{{bor+|bn|sa|जगत्|জগৎ}}. Cognate with {{cog|as...,"[{'name': 'glossary', 'args': {'1': 'loanword'..."