In [ ]:
import os
import polars as pl
import json
from tqdm import tqdm

from etytreealg.decode import langcodes as langcodes

def load_df():
    df_dest = '../data/parquet/ety_expanded.parquet'
    return pl.read_parquet(df_dest)

def hydrate_df(df):
    """
    Call json.loads on the columns that are stored as JSON strings
    which are templates, related, and descendants
    """

    # note that Object datatype cannot be written to parquet/arrow
    df = df.with_columns([
        pl.col('templates').map_elements(lambda x: json.loads(x) if x else [], return_dtype=pl.Object).alias('templates_h'),
        pl.col('related').map_elements(lambda x: json.loads(x) if x else [], return_dtype=pl.Object).alias('related_h'),
        pl.col('descendants').map_elements(lambda x: json.loads(x) if x else [], return_dtype=pl.Object).alias('descendants_h'),
    ])

    df = df.drop(['templates', 'related', 'descendants'])

    print("Hydrated!")
    return df
def collate_templates(df, desired_templates):
    """
    collate the templates by their type
    """
    collated_templates = {x: [] for x in desired_templates}
    for templates in df['templates_h']:
        if not templates:
            continue
        for template in templates:
            if template['name'] in desired_templates:
                collated_templates[template['name']].append(template['args'])
    return collated_templates

def lang_sr_by_template_arg(args):
    """
    get empirical rate that a template argument is a langcode
    """
    from etytreealg.decode import langcodes as langcodes
    sr_by_arg = {} # success rate by key
    for arg in args:
        for key, value in arg.items():
            if key not in sr_by_arg:
                sr_by_arg[key] = {'success': 0, 'total': 0}
            if value:
                sr_by_arg[key]['total'] += 1
                if langcodes.is_langcode(value):
                    sr_by_arg[key]['success'] += 1
    return sr_by_arg



def predicted_lang_args_per_template(lang_success_rates, debug=False):
    """
    Empirically determine which arguments are likely to be lang codes in a given template.
    Does this based on the success rate of a key being a lang code.
    Returns a dictionary of template: str -> set[str]

    Criteria for being a suspected lang key
    1. key contains 'lang' OR
    2. success rate > 95% AND total > 5

    If debug is True, then we also return the warning keys, where the success rate is between 0.8 and 0.95.

    We have exceptions: 

    1. Han compound's 'ls' is one of ['i', 'ic', 'psc'] but do NOT represent langcodes
    2. Same for liushu: ['p', 'i', 'ic', 'psc']

    4. surface analysis & surf 1 can be a lang, but surf 1 can also be a reference to another template
    (like +suf)
    5. noncog contains a large frequency of language families, due to its migration from {{etyl}}
    6. Hira-dakuten 2 is actually Hepburn romanization of the character, which happens to be a lot of used 2- or 3- letter codes
    7. Kana-dakuten: same
    8. wp & zh-wp's argument is technically a lang code, but not the exact same one https://en.wiktionary.org/wiki/Template:wikipedia
    9. cog 1 may be a comma-separated list of langcodes. The same is true of bor 2, bor+ 2, 
    (1 instance only:) clq 2, cal 2, ubor 2, ncog 1,
    10. dercat may have "<" in fields normally occupied by a language.
    11. inc-ext looks confusing
    12. pi-root 1 and tl-bay sc are NOT languages

    """
    suspected_lang_keys_per_template = {}
    _warning_keys = {}
    for template, sr in lang_success_rates.items():
        # criteria for being a suspected lang key
        # 1. key contains 'lang' OR
        # 2. success rate > 95% AND total > 5
        suspected_lang_keys = {k for k, v in sr.items() if 'lang' in k or v['total'] and v['total'] >= 5 and v['success'] / v['total'] >= 0.95}
        
        # check for those between 0.8 and 0.95 and print them as a warning: usually, 
        for k, v in sr.items():
            if v['total'] and v['total'] >= 5 and 0.5 <= v['success'] / v['total'] < .9999:
                # print(f"WARNING: {template} {k} {v['success'] / v['total']:.2%}")
                _warning_keys[(template, k)] = v['success'] / v['total']
        
        suspected_lang_keys_per_template[template] = list(suspected_lang_keys)
    if debug:
        return suspected_lang_keys_per_template, _warning_keys
    return suspected_lang_keys_per_template

In [41]:
df = load_df()
df = df.with_row_index("index")

In [65]:
df = hydrate_df(df)

Hydrated!

In [16]:
df

shape: (9_633_555, 11)
┌─────────┬────────────┬─────────┬───────────┬───┬───────────┬────────────┬───────────┬────────────┐
│ index   ┆ word       ┆ lang    ┆ lang_code ┆ … ┆ forms_of  ┆ templates_ ┆ related_h ┆ descendant │
│ ---     ┆ ---        ┆ ---     ┆ ---       ┆   ┆ ---       ┆ h          ┆ ---       ┆ s_h        │
│ u32     ┆ str        ┆ str     ┆ str       ┆   ┆ list[str] ┆ ---        ┆ object    ┆ ---        │
│         ┆            ┆         ┆           ┆   ┆           ┆ object     ┆           ┆ object     │
╞═════════╪════════════╪═════════╪═══════════╪═══╪═══════════╪════════════╪═══════════╪════════════╡
│ 0       ┆            ┆         ┆           ┆ … ┆ null      ┆ null       ┆ null      ┆ null       │
│ 1       ┆ apples and ┆ English ┆ en        ┆ … ┆ null      ┆ null       ┆ null      ┆ null       │
│         ┆ pears      ┆         ┆           ┆   ┆           ┆            ┆           ┆            │
│ 2       ┆ abhal      ┆ English ┆ en        ┆ … ┆ null      ┆ [{'name':  ┆ null      ┆ null       │
│         ┆            ┆         ┆           ┆   ┆           ┆ 'der',     ┆           ┆            │
│         ┆            ┆         ┆           ┆   ┆           ┆ 'args':    ┆           ┆            │
│         ┆            ┆         ┆           ┆   ┆           ┆ {'1':…     ┆           ┆            │
│ 3       ┆ abaisance  ┆ English ┆ en        ┆ … ┆ null      ┆ [{'name':  ┆ null      ┆ null       │
│         ┆            ┆         ┆           ┆   ┆           ┆ 'der',     ┆           ┆            │
│         ┆            ┆         ┆           ┆   ┆           ┆ 'args':    ┆           ┆            │
│         ┆            ┆         ┆           ┆   ┆           ┆ {'1':…     ┆           ┆            │
│ 4       ┆ A 1        ┆ English ┆ en        ┆ … ┆ null      ┆ null       ┆ null      ┆ null       │
│ …       ┆ …          ┆ …       ┆ …         ┆ … ┆ …         ┆ …          ┆ …         ┆ …          │
│ 9633550 ┆ copulate   ┆ English ┆ en        ┆ … ┆ null      ┆ null       ┆ null      ┆ null       │
│         ┆ with       ┆         ┆           ┆   ┆           ┆            ┆           ┆            │
│ 9633551 ┆ physical   ┆ English ┆ en        ┆ … ┆ null      ┆ null       ┆ null      ┆ null       │
│         ┆ property   ┆         ┆           ┆   ┆           ┆            ┆           ┆            │
│ 9633552 ┆ unit of    ┆ English ┆ en        ┆ … ┆ null      ┆ null       ┆ null      ┆ null       │
│         ┆ measure    ┆         ┆           ┆   ┆           ┆            ┆           ┆            │
│ 9633553 ┆ government ┆ English ┆ en        ┆ … ┆ null      ┆ null       ┆ null      ┆ null       │
│         ┆ minister   ┆         ┆           ┆   ┆           ┆            ┆           ┆            │
│ 9633554 ┆ incorrect  ┆ English ┆ en        ┆ … ┆ null      ┆ null       ┆ null      ┆ null       │
│         ┆ argument   ┆         ┆           ┆   ┆           ┆            ┆           ┆            │
└─────────┴────────────┴─────────┴───────────┴───┴───────────┴────────────┴───────────┴────────────┘

In [66]:
with open('../data/templates/template_freqs.json', 'r') as f:
    sorted_template_frequencies = json.load(f)

In [67]:
desired_templates = [template for template, freq in sorted_template_frequencies if freq >= 20]

collated_templates = collate_templates(df, desired_templates)

In [8]:
collated_templates['der']

[{'1': 'en', '2': 'ar', '3': 'أَبْهَل'},
 {'1': 'en', '2': 'fro', '3': 'abaissance'},
 {'1': 'en', '2': 'la', '3': 'fabaceus'},
 {'1': 'fr', '2': 'fro', '3': 'abisme'},
 {'1': 'fr', '2': 'VL.', '3': '*abyssimus'},
 {'1': 'fr', '2': 'grc', '3': 'ἄβυσσος'},
 {'1': 'mfe', '2': 'fr', '3': 'abîmer'},
 {'1': 'en', '2': 'la', '3': 'abāctiō'},
 {'1': 'en', '2': 'la', '3': '-'},
 {'1': 'enm',
  '2': 'fro',
  '3': 'abaubir',
  '4': '',
  '5': 'to frighten, disconcert'},
 {'1': 'enm', '2': 'la', '3': 'ad-'},
 {'1': 'en', '2': 'la', '3': 'abies', '4': '', '5': 'silver fir (tree)'},
 {'1': 'en', '2': 'la', '3': 'ab'},
 {'1': 'en',
  '2': 'la',
  '3': 'abditīvus',
  '4': '',
  '5': 'removed or separated from'},
 {'1': 'en', '2': 'la', '3': 'abalienatio'},
 {'1': 'oc', '2': 'la', '3': 'grātuītus'},
 {'1': 'ro', '2': 'la', '3': 'gratuitus'},
 {'1': 'en', '2': 'la', '3': 'ab', 't': 'from'},
 {'1': 'en', '2': 'la', '3': 'abiudicare'},
 {'1': 'en', '2': 'la', '3': 'abiugātus'},
 {'1': 'en', '2': 'NL.', '3': '-'},
 {'1': 'en',
  '2': 'grc',
  '3': 'ἀβακίσκος',
  '4': '',
  '5': 'a coloured stone for laying mosaic'},
 {'1': 'en', '2': 'enm', '3': '-'},
 {'1': 'en', '2': 'ML.', '3': 'abacista'},
 {'1': 'en', '2': 'la', '3': 'ablactātus'},
 {'1': 'en',
  '2': 'la',
  '3': 'ablēgātio',
  '4': '',
  '5': 'a sending away, banishment'},
 {'1': 'en',
  '2': 'la',
  '3': 'ablaqueātiō',
  '4': '',
  '5': 'the process or act of digging or loosening the soil around the roots of a tree'},
 {'1': 'en', '2': 'la', '3': 'abiūnctus'},
 {'1': 'en', '2': 'LL.', '3': 'abula'},
 {'1': 'mul', '2': 'la', '3': 'abies', '4': '', '5': 'silver fir'},
 {'1': 'en', '2': 'xno', '3': '-'},
 {'1': 'en', '2': 'fro', '3': 'abeter'},
 {'1': 'en', '2': 'la', '3': 'ablūdō', '4': '', '5': 'differ from'},
 {'1': 'en', '2': 'xno', '3': '-'},
 {'1': 'en', '2': 'fro', '3': '-'},
 {'1': 'en', '2': 'LL.', '3': 'abacinātus'},
 {'1': 'en', '2': 'la', '3': 'abaliēnātus'},
 {'1': 'en', '2': 'LL.', '3': 'abecedarius'},
 {'1': 'en', '2': 'LL.', '3': 'abecedarius'},
 {'1': 'en', '2': 'fro', '3': 'aubel'},
 {'1': 'en', '2': 'la-med', '3': 'albellus', '4': '', '5': 'white poplar'},
 {'1': 'en', '2': 'la', '3': 'albus', '4': '', '5': 'white'},
 {'1': 'en', '2': 'dum', '3': 'abeel'},
 {'1': 'en', '2': 'ML.', '3': 'abditorium'},
 {'1': 'en',
  '2': 'ak',
  '3': 'aboma',
  '4': '',
  '5': 'large constricting snake'},
 {'1': 'en', '2': 'fr', '3': 'aboma'},
 {'1': 'en', '2': 'la', '3': 'faba', 't': 'bean'},
 {'1': 'gv', '2': 'la', '3': 'abbās'},
 {'1': 'gv', '2': 'grc', '3': 'ἀββᾶς'},
 {'1': 'gv',
  '2': 'arc',
  '3': 'אבא',
  '4': '',
  '5': 'father',
  'tr': '’abbā',
  'sc': 'Hebr'},
 {'1': 'en', '2': 'la', '3': 'abdicativus'},
 {'1': 'en', '2': 'la', '3': 'abaculus'},
 {'1': 'la', '2': 'grc', '3': 'ἄβαξ', '4': '', '5': 'board'},
 {'1': 'en',
  '2': 'la',
  '3': 'abiūrātiō',
  '4': '',
  '5': 'forswearing, abjuration'},
 {'1': 'fr',
  '2': 'la',
  '3': 'abiūrātiō',
  '4': 'abiūrātiōnem',
  '5': 'forswearing, abjuration'},
 {'1': 'en', '2': 'la', '3': 'ablēgātus'},
 {'1': 'en', '2': 'la', '3': 'ablēgātus'},
 {'1': 'en', '2': 'frm', '3': 'abaissement', 't': 'astonishment'},
 {'1': 'en', '2': 'enm', '3': 'baft'},
 {'1': 'en', '2': 'ang', '3': 'beæftan'},
 {'1': 'en', '2': 'enm', '3': 'baft'},
 {'1': 'en', '2': 'ang', '3': 'beæftan'},
 {'1': 'en', '2': 'la', '3': 'abhominalis'},
 {'1': 'en',
  '2': 'la',
  '3': 'aberrare',
  '4': 'aberrō',
  '5': 'to wander from the way'},
 {'1': 'en', '2': 'fa-cls', '3': 'آبْدَسْت'},
 {'1': 'pl', '2': 'fa', '3': 'آبدست'},
 {'1': 'sh', '2': 'fa', '3': 'آبدست', 'tr': 'âbdast'},
 {'1': 'tr', '2': 'fa', '3': 'آبدست', 'tr': 'âbdast'},
 {'1': 'en', '2': 'la', '3': '-'},
 {'1': 'en', '2': 'fro', '3': 'abateure'},
 {'1': 'en', '2': 'la', '3': 'abnormis', '4': '', '5': 'irregular, abnormal'},
 {'1': 'la',
  '2': 'grc',
  '3': 'ἐγκύκλιος παιδείᾱ',
  't': 'education in the circle of arts and sciences'},
 {'1': 'en', '2': 'ML.', '3': 'abbreviātūra'},
 {'1': 'en', '2': 'LL.', '3': 'abbreviō', '4': '', '5': 'shorten, abbreviate'},
 {'1': 'en', '2': 'NL.', '3': 'Abelmoschus', '4': 'abelmoschus'},
 {'1': 'en', '2': 'ar', '3': 'حَبّ الْمِسْك', 't': 'pills of musk'},
 {'1': 'en', '2': 'la', '3': 'facere', '4': '', '5': 'to make'},
 {'1': 'en', '2': 'la', '3': 'facere', '4': '', '5': 'to make'},
 {'1': 'en', '2': 'LL.', '3': 'ablactatio'},
 {'1': 'en', '2': 'frm', '3': 'abjection'},
 {'1': 'en', '2': 'LL.', '3': 'abiectiō', '4': 'abiectiōn-'},
 {'1': 'en', '2': 'la', '3': 'abiectus', '4': '', '5': 'cast down'},
 {'1': 'fr', '2': 'la', '3': 'abiectiō', '4': 'abiectiōnem'},
 {'1': 'en', '2': 'LL.', '3': 'abnegātiō'},
 {'1': 'en', '2': 'la', '3': 'abreptus'},
 {'1': 'en', '2': 'la', '3': 'ab-', 't': 'from'},
 {'1': 'en', '2': 'NL.', '3': '-'},
 {'1': 'en', '2': 'grc', '3': 'ἀ-', '4': '', '5': 'not'},
 {'1': 'en', '2': 'la', '3': 'abscisiō'},
 {'1': 'en', '2': 'goh', '3': 'aba', '4': '', '5': 'away'},
 {'1': 'en', '2': 'goh', '3': 'rūm'},
 {'1': 'en',
  '2': 'la',
  '3': 'sēsquipedālis',
  '4': '',
  '5': 'a foot and a half long; in metaphorical use, “of an unnatural length, huge, big”'},
 {'1': 'en', '2': 'la', '3': 'aberrō', '4': '', '5': 'go astray; err'},
 {'1': 'en', '2': 'frm', '3': 'abdication'},
 {'1': 'en', '2': 'la', '3': 'abdicātiō', '4': '', '5': 'renunciation'},
 {'1': 'en', '2': 'LL.', '3': 'ablātiō', 't': 'a taking away'},
 {'1': 'enm', '2': 'la', '3': 'abbreviō'},
 {'1': 'en',
  '2': 'la',
  '3': 'denoto',
  '4': 'dēnotāre',
  't': 'to denote, mark out'},
 {'1': 'en', '2': 'fro', '3': 'patronage'},
 {'1': 'en', '2': 'fro', '3': 'patronage'},
 {'1': 'en', '2': 'la', '3': 'abscindere'},
 {'1': 'en', '2': 'la', '3': 'Fabiānus', '4': '', '5': 'belonging to Fabius'},
 {'1': 'en', '2': 'la', '3': 'Fabiānus', '4': '', '5': 'belonging to Fabius'},
 {'1': 'en', '2': 'la', '3': 'Fabiānus', '4': '', '5': 'belonging to Fabius'},
 {'1': 'en', '2': 'la', '3': 'Abderita'},
 {'1': 'en', '2': 'grc', '3': 'Ἀβδηρίτης'},
 {'1': 'en', '2': 'fro', '3': 'abrenonciation'},
 {'1': 'en', '2': 'LL.', '3': 'abrenuntiatio'},
 {'1': 'en', '2': 'LL.', '3': 'abrenuntiatiō'},
 {'1': 'en', '2': 'la', '3': 'abdūcō', '4': '', '5': 'lead away'},
 {'1': 'en', '2': 'la', '3': 'irrītō', 't': 'to irritate'},
 {'1': 'en', '2': 'la', '3': 'irrītō', 't': 'to irritate'},
 {'1': 'en', '2': 'nrf', '3': '-'},
 {'1': 'en', '2': 'fro', '3': 'abroche', '4': '', '5': 'to spigot'},
 {'1': 'en', '2': 'nrf', '3': '-'},
 {'1': 'en', '2': 'fro', '3': 'abroche', '4': '', '5': 'to spigot'},
 {'1': 'en', '2': 'nrf', '3': '-'},
 {'1': 'en', '2': 'fro', '3': 'abroche', '4': '', '5': 'to spigot'},
 {'1': 'en', '2': 'fro', '3': 'barater'},
 {'1': 'en', '2': 'fro', '3': 'barater'},
 {'1': 'id', '2': 'en', '3': 'barter'},
 {'1': 'id', '2': 'enm', '3': '-'},
 {'1': 'id', '2': 'fro', '3': 'barater'},
 {'1': 'pl', '2': 'enm', '3': '-'},
 {'1': 'pl', '2': 'fro', '3': 'barater'},
 {'1': 'en', '2': 'gem-pro', '3': '*uz-', 't': 'out'},
 {'1': 'en', '2': 'ine-pro', '3': '*bʰrēḱ-'},
 {'1': 'en', '2': 'la', '3': 'abrāsus'},
 {'1': 'en', '2': 'la', '3': 'abrāsus'},
 {'1': 'en', '2': 'fr', '3': 'abord'},
 {'1': 'fr',
  '2': 'fro',
  '3': 'aborder',
  't': 'to hit a ship in order to board it'},
 {'1': 'fr', '2': 'frk', '3': '*bord', 't': 'side of a ship or vessel'},
 {'1': 'fr', '2': 'gem-pro', '3': '*burdą', 't': 'edge, border, side'},
 {'1': 'fr', '2': 'ine-pro', '3': '*bheredh-', 't': 'to cut'},
 {'1': 'en', '2': 'frm', '3': 'abbatial'},
 {'1': 'en', '2': 'LL.', '3': 'abbatialis'},
 {'1': 'fr', '2': 'LL.', '3': 'abbātiālis', '4': '', '5': 'abbatial'},
 {'1': 'fr', '2': 'LL.', '3': 'abbātiālis', '4': '', '5': 'abbatial'},
 {'1': 'en', '2': 'la', '3': 'abrogō'},
 {'1': 'en', '2': 'ML.', '3': 'absentatio', '4': ''},
 {'1': 'en', '2': 'la', '3': 'absento', '4': '', '5': 'to be absent'},
 {'1': 'en', '2': 'ine-pro', '3': '*h₂epo', '4': '', '5': 'off, away'},
 {'1': 'de', '2': 'gmh', '3': 'abe, ab'},
 {'1': 'de', '2': 'goh', '3': 'ab'},
 {'1': 'de', '2': 'gmw-pro', '3': '*ab(a)'},
 {'1': 'de', '2': 'gem-pro', '3': '*ab'},
 {'1': 'id', '2': 'la', '3': 'ab-'},
 {'1': 'id', '2': 'ine-pro', '3': '*h₂epo', '4': '', '5': 'off, away'},
 {'1': 'it', '2': 'la', '3': 'ab', '4': '', '5': 'from, away from'},
 {'1': 'en', '2': 'la-ecc', '3': 'abbreviātor'},
 {'1': 'nl', '2': 'ine-pro', '3': '*kerp-'},
 {'1': 'en',
  '2': 'ML.',
  '3': 'abecedārium',
  '4': '',
  '5': 'alphabet, ABC primer'},
 {'1': 'en', '2': 'LL.', '3': 'abecedārius', '4': '', '5': 'of the alphabet'},
 {'1': 'fro', '2': 'frk', '3': '*bann'},
 {'1': 'fro', '2': 'gem-pro', '3': '*bannaną'},
 {'1': 'en', '2': 'LL.', '3': 'abōminātus'},
 {'1': 'en', '2': 'LL.', '3': 'abōminātus'},
 {'1': 'en', '2': 'xno', '3': 'abaiss', '4': 'abaïss'},
 {'1': 'en', '2': 'frm', '3': 'abair'},
 {'1': 'en', '2': 'fro', '3': 'esbair', '4': 'esbaïr'},
 {'1': 'en', '2': 'ML.', '3': '*exbadō'},
 {'1': 'en', '2': 'LL.', '3': 'abbātia'},
 {'1': 'sco', '2': 'LL.', '3': 'abbātia'},
 {'1': 'en', '2': 'grc', '3': 'ὑπό', '4': '', '5': 'under'},
 {'1': 'en', '2': 'la', '3': 'abiūrō', 't': 'deny upon oath'},
 {'1': 'en', '2': 'frm', '3': 'abiurer', '4': 'abjurer'},
 {'1': 'en', '2': 'la', '3': 'abrogātiō', '4': '', '5': 'repealed'},
 {'1': 'fr',
  '2': 'la',
  '3': 'abrogātiō',
  '4': 'abrogātiōnem',
  '5': 'repealed'},
 {'1': 'fr', '2': 'la', '3': 'abrogō'},
 {'1': 'en', '2': 'LL.', '3': 'Abaddōn'},
 {'1': 'en', '2': 'grc', '3': 'Ἀβαδδών'},
 {'1': 'en',
  '2': 'hbo',
  '3': 'אבדון',
  'tr': 'ʾăḇaddōn',
  'lit': 'destruction, abyss'},
 {'1': 'en', '2': 'fr', '3': 'sémantique'},
 {'1': 'en', '2': 'grc', '3': 'σημαντικός'},
 {'1': 'en', '2': 'la', '3': 'sonans', 't': 'sound'},
 {'1': 'en', '2': 'fro', '3': 'ablatif', 't': 'the ablative case'},
 {'1': 'en', '2': 'la', '3': 'ablātīvus', 't': 'expressing removal'},
 {'1': 'en', '2': 'fro', '3': 'ablatif', 't': 'the ablative case'},
 {'1': 'en', '2': 'la', '3': 'ablātīvus', 't': 'expressing removal'},
 {'1': 'en', '2': 'la', '3': 'absumptio', '4': 'absumptionem'},
 {'1': 'id', '2': 'la', '3': 'abscissa'},
 {'1': 'fr', '2': 'ine-pro', '3': '*h₂eydʰ-', '4': '', '5': 'burn; fire'},
 {'1': 'en', '2': 'grc', '3': 'πνεύμων', '4': '', '5': 'lung'},
 {'1': 'en', '2': 'la', '3': 'ultra', '4': '', '5': 'beyond'},
 {'1': 'en', '2': 'grc', '3': 'κόνις', '4': '', '5': 'dust'},
 {'1': 'en', '2': 'ML.', '3': 'abstractivus'},
 {'1': 'en', '2': 'fr', '3': '-'},
 {'1': 'en', '2': 'frm', '3': 'absterger'},
 {'1': 'en', '2': 'ML.', '3': 'abstergēre'},
 {'1': 'en', '2': 'la', '3': 'abs-'},
 {'1': 'en', '2': 'la', '3': 'abductus'},
 {'1': 'mul', '2': 'NL.', '3': '-'},
 {'1': 'mul', '2': 'grc', '3': 'ἀκαλήφη', '4': '', '5': 'stinging nettle'},
 {'1': 'en', '2': 'frm', '3': 'abrégement'},
 {'1': 'en', '2': 'enm', '3': 'abatement'},
 {'1': 'en', '2': 'xno', '3': 'abatre', '4': '', '5': 'to abate'},
 {'1': 'en', '2': 'fro', '3': 'abatre'},
 {'1': 'en', '2': 'mul', '3': 'Acanthocephala'},
 {'1': 'en', '2': 'frm', '3': 'abomination', 't': 'horror, disgust'},
 {'1': 'en',
  '2': 'LL.',
  '3': 'abōminātiō',
  '4': 'abōminātiō, abōminātiōnem',
  't': 'abomination'},
 {'1': 'fr', '2': 'LL.', '3': 'abōminātiōnem'},
 {'1': 'en', '2': 'grc', '3': 'ἀκαλήφη', '4': '', '5': 'stinging nettle'},
 {'1': 'en', '2': 'frm', '3': 'abolition'},
 {'1': 'en', '2': 'la', '3': 'abolitiō'},
 {'1': 'fr', '2': 'la', '3': 'abolitionem'},
 {'1': 'en', '2': 'fro', '3': 'abai'},
 {'1': 'en', '2': 'la', '3': 'abstersus'},
 {'1': 'mul', '2': 'NL.', '3': '-'},
 {'1': 'mul', '2': 'ar', '3': 'أَبُو طِيلُون', '4': '', '5': 'Indian mallow'},
 {'1': 'frm', '2': 'la', '3': 'liber'},
 {'1': 'frm', '2': 'la', '3': 'līber'},
 {'1': 'nrf', '2': 'la', '3': 'libra'},
 {'1': 'en', '2': 'la', '3': 'abstrūdō', '4': '', '5': 'push away, hide'},
 {'1': 'en', '2': 'fro', '3': '-'},
 {'1': 'en', '2': 'ML.', '3': 'abstertion'},
 {'1': 'en', '2': 'la', '3': 'abstersus'},
 {'1': 'en', '2': 'fro', '3': 'ablution'},
 {'1': 'en', '2': 'LL.', '3': 'ablūtiō', '4': '', '5': 'a washing away'},
 {'1': 'en', '2': 'la', '3': 'caulis', '4': '', '5': 'stalk'},
 {'1': 'en', '2': 'xno', '3': 'abeiance', '4': '', '5': 'legal expectation'},
 {'1': 'en', '2': 'fro', '3': 'abeance', '4': '', '5': 'desire'},
 {'1': 'mul', '2': 'NL.', '3': '-'},
 {'1': 'mul', '2': 'grc', '3': 'ἄκανθα', '4': '', '5': 'spine'},
 {'1': 'en', '2': 'grc', '3': 'ἄκανθα', '4': '', '5': 'thorn'},
 {'1': 'en', '2': 'fro', '3': 'abusion'},
 {'1': 'en', '2': 'la', '3': 'abūsiō', '4': '', '5': 'abuse, misuse'},
 {'1': 'en', '2': 'grc', '3': 'ἄκανθος'},
 {'1': 'en', '2': 'css', '3': 'aulun', '4': 'aūlun', '5': 'red abalone'},
 {'1': 'ms', '2': 'es', '3': 'abulón'},
 {'1': 'ms', '2': 'css', '3': 'aulun', '4': 'aūlun', '5': 'red abalone'},
 {'1': 'en', '2': 'frm', '3': 'abstersif'},
 {'1': 'en', '2': 'la', '3': 'abstersus'},
 {'1': 'en', '2': 'frm', '3': 'abstersif'},
 {'1': 'en', '2': 'la', '3': 'abstersus'},
 {'1': 'en', '2': 'fro', '3': 'abregier'},
 {'1': 'en',
  '2': 'LL.',
  '3': 'abbrevio',
  '4': 'abbreviō, abberiāre',
  't': 'make brief'},
 {'1': 'en', '2': 'grc', '3': 'ἀκαρί', '4': '', '5': 'mite'},
 {'1': 'en', '2': 'tl', '3': 'abaka'},
 {'1': 'fr', '2': 'es', '3': 'abacá'},
 {'1': 'fr', '2': 'tl', '3': '-'},
 {'1': 'nb', '2': 'en', '3': 'abaca'},
 {'1': 'nb', '2': 'es', '3': 'abacá', '4': '', '5': 'abaca, Manilla hemp'},
 {'1': 'nb', '2': 'tl', '3': 'abaka', '4': '', '5': 'abaca, Manilla hemp'},
 {'1': 'nb', '2': 'ar', '3': 'أَبَق', '4': '', '5': 'abaca'},
 {'1': 'nb', '2': 'syc', '3': 'ܐܳܦܰܩܬܳܐ', 'tr': 'ʾāpaqtā'},
 {'1': 'en', '2': 'grc', '3': 'Ἀκαδημία'},
 {'1': 'en', '2': 'la', '3': 'accendere', '4': '', '5': 'to kindle'},
 {'1': 'en', '2': 'fro', '3': 'abonder'},
 {'1': 'en', '2': 'la', '3': 'abundāre'},
 {'1': 'ro', '2': 'la', '3': 'absolvens'},
 {'1': 'en', '2': 'la', '3': '-'},
 {'1': 'en', '2': 'grc', '3': '-'},
 {'1': 'en', '2': 'arc', 'sc': 'Hebr', '3': 'אבא'},
 {'1': 'it', '2': 'grc', '3': 'ἀββα'},
 {'1': 'it', '2': 'arc', 'sc': 'Hebr', '3': 'אבא'},
 {'1': 'la', '2': 'arc', 'sc': 'Hebr', '3': 'אבא'},
 {'1': 'nb', '2': 'la', '3': 'abba', '4': '', '5': 'father'},
 {'1': 'nb',
  '2': 'grc',
  '3': 'ἀββα',
  '4': '',
  '5': 'father, title of respect given to abbots'},
 {'1': 'nb',
  '2': 'arc',
  '3': 'אבא',
  '4': '',
  '5': 'father, teacher, ancestor, leader',
  'tr': '’abbā',
  'sc': 'Hebr'},
 {'1': 'nb', '2': 'sem-pro', '3': '*ʔabw-', '4': '', '5': 'father'},
 {'1': 'nb', '2': 'afa-pro', '3': '*ʔab-'},
 {'1': 'mul', '2': 'grc', '3': 'ἄκανθος', '4': '', '5': 'thorn'},
 {'1': 'en', '2': 'la', '3': 'con-', 't': 'together, with'},
 {'1': 'fr', '2': 'la', '3': 'con-', 't': 'together, with'},
 {'1': 'de', '2': 'la', '3': 'ab-'},
 {'1': 'pt', '2': 'la', '3': 'ab-'},
 {'1': 'en',
  '2': 'la',
  '3': 'acceptilatio',
  '4': '',
  '5': 'entry of a debt collected, acquittance'},
 {'1': 'en', '2': 'fro', '3': 'acordement'},
 {'1': 'en', '2': 'frm', '3': 'abhorrer'},
 {'1': 'en',
  '2': 'la',
  '3': 'abhorreō',
  '4': '',
  '5': 'shrink away from in horror'},
 {'1': 'en', '2': 'la', '3': 'abductiō', 't': 'robbing; abduction'},
 {'1': 'en', '2': 'la', '3': 'abductus'},
 {'1': 'ia', '2': 'la', '3': 'abductiō', 't': 'robbing; abduction'},
 {'1': 'en',
  '2': 'grc',
  '3': 'θησαυρός',
  '4': '',
  '5': 'storehouse, treasure'},
 {'1': 'la',
  '2': 'grc',
  '3': 'θησαυρός',
  '4': '',
  '5': 'storehouse, treasure'},
 {'1': 'en', '2': 'fro', '3': 'encloyer'},
 {'1': 'en', '2': 'ML.', '3': 'inclavare'},
 {'1': 'en', '2': 'la', '3': '-'},
 {'1': 'en', '2': 'ms', '3': 'badak', '4': '', '5': 'rhinoceros'},
 {'1': 'bm', '2': 'ar', '3': 'أَبَد', '4': '', '5': 'eternity'},
 {'1': 'bm', '2': 'ar', '3': 'أَبَد', '4': '', '5': 'eternity'},
 {'1': 'es', '2': 'ms', '3': 'badak'},
 {'1': 'en', '2': 'LL.', '3': 'abactor', '4': '', '5': 'cattle rustler'},
 {'1': 'en', '2': 'fr', '3': 'acclimatation'},
 {'1': 'en', '2': 'NL.', '3': '-'},
 {'1': 'en', '2': 'grc', '3': 'ἄκανθος'},
 {'1': 'en', '2': 'grc', '3': 'πτερύγιον'},
 {'1': 'en', '2': 'NL.', '3': '-'},
 {'1': 'en', '2': 'grc', '3': 'ἄκανθος'},
 {'1': 'en', '2': 'grc', '3': 'πτερύγιον'},
 {'1': 'en', '2': 'frm', '3': 'accomodable'},
 {'1': 'en', '2': 'fro', '3': 'acoillir'},
 {'1': 'en', '2': 'VL.', '3': '*accolligere'},
 {'1': 'en', '2': 'la', '3': 'ad-'},
 {'1': 'en', '2': 'frm', '3': 'acoyer'},
 {'1': 'en', '2': 'la', '3': 'absinthium'},
 {'1': 'en', '2': 'grc', '3': 'ἀψίνθιον'},
 {'1': 'en', '2': 'frm', '3': 'accepcion'},
 {'1': 'en',
  '2': 'la',
  '3': 'acceptiō',
  '4': 'acceptiō, acceptiōnis',
  '5': 'acceptance'},
 {'1': 'en', '2': 'grc', '3': 'ἀκαρί', 't': 'cheese mite, tick'},
 {'1': 'en', '2': 'fro', '3': 'acrochier', '4': '', '5': 'to hook in'},
 {'1': 'en', '2': 'fro', '3': 'abeesse'},
 {'1': 'en', '2': 'LL.', '3': '-'},
 {'1': 'en', '2': 'EL.', '3': 'abbatissa'},
 {'1': 'en', '2': 'la', '3': 'abbas'},
 {'1': 'en', '2': 'fro', '3': 'substantif'},
 {'1': 'en', '2': 'fro', '3': 'substantif'},
 {'1': 'en', '2': 'fro', '3': 'substantif'},
 {'1': 'ms', '2': 'la', '3': 'ab-', 't': 'away from'},
 {'1': 'en', '2': 'xno', '3': 'acordable'},
 {'1': 'it', '2': 'la', '3': 'acclīvis'},
 {'1': 'en',
  '2': 'fr',
  '3': 'auguste',
  '4': '',
  '5': 'noble, stately; august'},
 {'1': 'en',
  '2': 'la',
  '3': 'augustus',
  '4': '',
  '5': 'majestic, venerable, august; imperial, royal'},
 {'1': 'en', '2': 'la', '3': 'ama'},
 {'1': 'en', '2': 'grc', '3': 'ἄμη', '4': '', '5': 'bucket'},
 {'1': 'af', '2': 'la', '3': 'ama'},
 {'1': 'af', '2': 'grc', '3': 'ἄμη', '4': '', '5': 'bucket'},
 {'1': 'nl', '2': 'LL.', '3': 'ama'},
 {'1': 'nl', '2': 'grc', '3': 'ἄμη', '4': '', '5': 'bucket'},
 {'1': 'et', '2': 'gml', '3': 'am'},
 {'1': 'et', '2': 'la', '3': 'hama', '4': 'ama', '5': 'firebucket'},
 {'1': 'et', '2': 'grc', '3': 'ᾰ̓́μη', '4': '', '5': 'bucket'},
 {'1': 'en', '2': 'grc', '3': 'ἀ-', 't': 'not-', 'pos': 'the alpha privative'},
 {'1': 'en', '2': 'ine-pro', '3': '*gʷeyh₃-', 't': 'to live'},
 {'1': 'en', '2': 'ine-pro', '3': '*ǵénh₁tis', 't': 'birth; production'},
 {'1': 'en', '2': 'dum', '3': 'aerde'},
 {'1': 'en', '2': 'dum', '3': 'varken'},
 {'1': 'en', '2': 'la-cla', '3': 'acciō', '4': '', '5': 'call forth'},
 {'1': 'en', '2': 'pt', '3': 'acaju'},
 {'1': 'en', '2': 'tpw', '3': 'acaju'},
 {'1': 'en', '2': 'fro', '3': 'abeter', '4': '', '5': 'to entice'},
 {'1': 'en', '2': 'dum', '3': 'betan', '4': 'bētan', '5': 'incite'},
 {'1': 'en',
  '2': 'non',
  '3': 'beita',
  '4': '',
  '5': 'to cause to bite, bait, incite'},
 {'1': 'en',
  '2': 'gem-pro',
  '3': '*baitijaną',
  '4': '',
  '5': 'to cause to bite'},
 {'1': 'en', '2': 'ine-pro', '3': '*bʰeyd-', '4': '', '5': 'to split'},
 {'1': 'en', '2': 'gem-pro', '3': '*baitijaną'},
 {'1': 'en', '2': 'fro', '3': 'abeter', '4': '', '5': 'to entice'},
 {'1': 'en', '2': 'dum', '3': 'betan', '4': 'bētan', '5': 'incite'},
 {'1': 'en',
  '2': 'non',
  '3': 'beita',
  '4': '',
  '5': 'to cause to bite, bait, incite'},
 {'1': 'en',
  '2': 'gem-pro',
  '3': '*baitijaną',
  '4': '',
  '5': 'to cause to bite'},
 {'1': 'en', '2': 'ine-pro', '3': '*bʰeyd-', '4': '', '5': 'to split'},
 {'1': 'en', '2': 'gem-pro', '3': '*baitijaną'},
 {'1': 'en', '2': 'xno', '3': 'accidie'},
 {'1': 'en', '2': 'fro', '3': 'accide'},
 {'1': 'en', '2': 'LL.', '3': 'accīdia'},
 {'1': 'en', '2': 'grc', '3': 'ἀκήδεια', '4': '', '5': 'indifference'},
 {'1': 'enm', '2': 'LL.', '3': 'accīdia'},
 {'1': 'enm', '2': 'grc', '3': 'ἀκήδεια'},
 {'1': 'en', '2': 'ML.', '3': 'abyssalis'},
 {'1': 'en', '2': 'la', '3': 'abyssus', '4': '', '5': 'abyss'},
 {'1': 'fr', '2': 'LL.', '3': 'abyssālis'},
 {'1': 'en', '2': 'la', '3': 'accidentia', '4': '', '5': 'accidental matters'},
 {'1': 'en', '2': 'grc', '3': 'ἄχροος'},
 {'1': 'en', '2': 'frm', '3': 'aboliss-'},
 {'1': 'en',
  '2': 'la',
  '3': 'aboleo',
  '4': 'abolēre',
  '5': 'to retard, check the growth of, (and by extension) destroy, abolish'},
 {'1': 'en', '2': 'ML.', '3': 'abrasio', '4': '', '5': 'a scraping'},
 {'1': 'en', '2': 'la', '3': 'abrādō', '4': '', '5': 'scrape off'},
 {'1': 'en', '2': 'fro', '3': 'abaie', '4': 'abaïe'},

In [ ]:
lang_success_rates = {tname: lang_sr_by_template_arg(t_examples) for tname, t_examples in collated_templates.items()}

In [ ]:
lang_success_rates['der']

{'1': {'success': 276399, 'total': 276399},
 '2': {'success': 276390, 'total': 276399},
 '3': {'success': 2209, 'total': 268594},
 '4': {'success': 9, 'total': 9591},
 '5': {'success': 1106, 'total': 46334},
 't': {'success': 553, 'total': 26591},
 'tr': {'success': 228, 'total': 11233},
 'sc': {'success': 0, 'total': 554},
 'lit': {'success': 2, 'total': 1475},
 'pos': {'success': 18, 'total': 1479},
 'sort': {'success': 0, 'total': 2088},
 'ts': {'success': 18, 'total': 1002},
 'id': {'success': 28, 'total': 302},
 'g': {'success': 0, 'total': 415},
 'g2': {'success': 0, 'total': 0},
 'g3': {'success': 0, 'total': 0},
 'nocat': {'success': 0, 'total': 115},
 'gloss': {'success': 15, 'total': 846},
 'alt': {'success': 0, 'total': 135}}

In [24]:
all_words_set = df['word'].unique()

In [26]:
'hola' in all_words_set

True

In [27]:
type(all_words_set)

polars.series.series.Series

In [28]:
def word_sr_by_template_arg(args: list[dict[str, str]], known_lang_keys: list[str], all_words_set: pl.Series):
    """
    get empirical rate that a template argument is a word

    criteria for being a suspected word key:
    1. key is not a known LANG key
    
    metrics:
    1. word success rate: the value is present in all_words_set
    2. nonlatin rate: the value has at least one non-latin character


    """
    sr_by_arg = {} # word success rate by key
    for arg in args:
        for key, value in arg.items():
            if key in known_lang_keys:
                continue
            if key not in sr_by_arg:
                sr_by_arg[key] = {'total': 0, 'success': 0, 'nonlatin': 0}
            if value:
                sr_by_arg[key]['total'] += 1
                if value in all_words_set:
                    sr_by_arg[key]['success'] += 1
                if not value.isascii():
                    sr_by_arg[key]['nonlatin'] += 1
                
    return sr_by_arg

In [36]:
suspected_lang_keys_per_template, _warning_keys = predicted_lang_args_per_template(lang_success_rates, debug=True)

In [39]:
all_words_set = set(all_words_set)

In [41]:
'hola' in all_words_set

True

In [46]:
df.filter(pl.col('lang').str.starts_with('Proto-'))

shape: (34_678, 11)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ index   ┆ word       ┆ lang      ┆ lang_code ┆ … ┆ num_templ ┆ related   ┆ descendan ┆ forms_of  │
│ ---     ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ates      ┆ ---       ┆ ts        ┆ ---       │
│ u32     ┆ str        ┆ str       ┆ str       ┆   ┆ ---       ┆ str       ┆ ---       ┆ list[str] │
│         ┆            ┆           ┆           ┆   ┆ u32       ┆           ┆ str       ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 94      ┆ frijaz     ┆ Proto-Ger ┆ gem-pro   ┆ … ┆ 2         ┆ [{"word": ┆ [{"depth" ┆ null      │
│         ┆            ┆ manic     ┆           ┆   ┆           ┆ "frija\u0 ┆ : 1, "tem ┆           │
│         ┆            ┆           ┆           ┆   ┆           ┆ 0few\u014 ┆ plates":  ┆           │
│         ┆            ┆           ┆           ┆   ┆           ┆ d"…       ┆ [{"…      ┆           │
│ 3819    ┆ wage       ┆ Proto-Nor ┆ gmq-pro   ┆ … ┆ 0         ┆ null      ┆ null      ┆ null      │
│         ┆            ┆ se        ┆           ┆   ┆           ┆           ┆           ┆           │
│ 12323   ┆ after      ┆ Proto-Nor ┆ gmq-pro   ┆ … ┆ 0         ┆ null      ┆ null      ┆ null      │
│         ┆            ┆ se        ┆           ┆   ┆           ┆           ┆           ┆           │
│ 13303   ┆ was        ┆ Proto-Nor ┆ gmq-pro   ┆ … ┆ 0         ┆ null      ┆ null      ┆ null      │
│         ┆            ┆ se        ┆           ┆   ┆           ┆           ┆           ┆           │
│ 21794   ┆ an         ┆ Proto-Nor ┆ gmq-pro   ┆ … ┆ 0         ┆ null      ┆ null      ┆ null      │
│         ┆            ┆ se        ┆           ┆   ┆           ┆           ┆           ┆           │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 9632368 ┆ leuþōn     ┆ Proto-Wes ┆ gmw-pro   ┆ … ┆ 2         ┆ null      ┆ [{"depth" ┆ null      │
│         ┆            ┆ t         ┆           ┆   ┆           ┆           ┆ : 1, "tem ┆           │
│         ┆            ┆ Germanic  ┆           ┆   ┆           ┆           ┆ plates":  ┆           │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆ [{"…      ┆           │
│ 9632457 ┆ frakwistij ┆ Proto-Wes ┆ gmw-pro   ┆ … ┆ 2         ┆ null      ┆ [{"depth" ┆ null      │
│         ┆ an         ┆ t         ┆           ┆   ┆           ┆           ┆ : 1, "tem ┆           │
│         ┆            ┆ Germanic  ┆           ┆   ┆           ┆           ┆ plates":  ┆           │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆ [{"…      ┆           │
│ 9632478 ┆ frakwistij ┆ Proto-Ger ┆ gem-pro   ┆ … ┆ 1         ┆ null      ┆ [{"depth" ┆ null      │
│         ┆ aną        ┆ manic     ┆           ┆   ┆           ┆           ┆ : 1, "tem ┆           │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆ plates":  ┆           │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆ [{"…      ┆           │
│ 9632536 ┆ lokkōn     ┆ Proto-Wes ┆ gmw-pro   ┆ … ┆ 1         ┆ [{"word": ┆ [{"depth" ┆ null      │
│         ┆            ┆ t         ┆           ┆   ┆           ┆ "leugan"} ┆ : 1, "tem ┆           │
│         ┆            ┆ Germanic  ┆           ┆   ┆           ┆ ]         ┆ plates":  ┆           │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆ [{"…      ┆           │
│ 9632537 ┆ mraʔ       ┆ Proto-Aus ┆ aav-pro   ┆ … ┆ 0         ┆ null      ┆ [{"depth" ┆ null      │
│         ┆            ┆ troasiati ┆           ┆   ┆           ┆           ┆ : 1, "tem ┆           │
│         ┆            ┆ c         ┆           ┆   ┆           ┆           ┆ plates":  ┆           │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆ [{"…      ┆           │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [42]:


# word_success_rates = {tname: word_sr_by_template_arg(t_examples, suspected_lang_keys_per_template.get(tname, []), all_words_set) for tname, t_examples in collated_templates.items()}


word_success_rates = {}
for tname, t_examples in tqdm(collated_templates.items()):
    suspected_lang_keys = suspected_lang_keys_per_template.get(tname, [])
    word_success_rates[tname] = word_sr_by_template_arg(t_examples, suspected_lang_keys, all_words_set)

100%|██████████| 331/331 [00:04<00:00, 71.89it/s]

In [48]:
word_success_rates['root']

{'3': {'total': 33476, 'success': 28528, 'nonlatin': 26764, 'unique': 3286},
 'id1': {'total': 106, 'success': 106, 'nonlatin': 0, 'unique': 32},
 '4': {'total': 1440, 'success': 1244, 'nonlatin': 1115, 'unique': 472},
 'id': {'total': 2682, 'success': 2672, 'nonlatin': 0, 'unique': 120},
 '5': {'total': 136, 'success': 125, 'nonlatin': 105, 'unique': 82},
 'id2': {'total': 114, 'success': 114, 'nonlatin': 0, 'unique': 37},
 'id3': {'total': 6, 'success': 6, 'nonlatin': 0, 'unique': 5},
 '6': {'total': 18, 'success': 14, 'nonlatin': 11, 'unique': 14},
 '7': {'total': 3, 'success': 3, 'nonlatin': 3, 'unique': 2},
 'sort': {'total': 1, 'success': 0, 'nonlatin': 0, 'unique': 1}}

In [35]:
import json

with open('../data/templates/word_sr.json', 'r') as f:
    word_success_rates = json.load(f)

In [60]:
def predicted_word_keys_per_template(word_success_rates, debug=False):
    """
    Criteria for being a WORD

    1. filter to only allow keys that are strictly numerical
    2. preference is given to the most common key
    3. preference is given to the key, strictly numerical, with the lowest value

    4. require that key has success rate > 30%
    5. preference is given if key has success rate > 80%
    """
    predicted_word_keys = {}
    nonlexical = set()

    def sr(v):
        return v['success'] / v['total'] if v['total'] else 0
    def unique_r(v):
        return v['unique'] / v['total'] if v['total'] else 0
    for template, srs_full in word_success_rates.items():
        # criteria for being a suspected lang key
        # 1. key contains 'lang' OR
        # 2. success rate > 95% AND total > 5
        suspected = set()
        
        success_rates = {k: v for k, v in srs_full.items() if k.isnumeric()}

        if not success_rates:
            predicted_word_keys[template] = []
            continue
        lowest_k = min(success_rates, key=lambda x: int(x))
        most_freq_k = max(success_rates, key=lambda x: success_rates[x]['total'])

        # give preference to these candidates
        if sr(success_rates[lowest_k]) > 0.3:
            suspected.add(lowest_k)
        if sr(success_rates[most_freq_k]) > 0.3:
            suspected.add(most_freq_k)

        # for the non-preferential, check for those between 0.3 and 0.8
        for k, v in success_rates.items():
            if sr(v) > 0.7 and unique_r(v) > 0.1:
                suspected.add(k)
                # print(f"WARNING: {template} {k} {v['success'] / v['total']:.2%}")
                pass
        
        if not suspected:
            # there are numerical keys, but none of them are words.
            # this is unusual, and should be noted
            nonlexical.add(template)
            

        
        predicted_word_keys[template] = sorted(suspected, key=lambda x: int(x))
    if debug:
        return predicted_word_keys, nonlexical
    return predicted_word_keys

In [61]:
predicted_word_keys, nonlexical = predicted_word_keys_per_template(word_success_rates, debug=True)

In [50]:
predicted_word_keys['cog']

['2']

In [62]:
multilexical = {k: v for k, v in predicted_word_keys.items() if len(v) > 1}

In [63]:
multilexical

{'af': ['2', '3', '4', '5', '6', '7', '9', '10'],
 'suffix': ['2', '3', '4', '5', '6'],
 'affix': ['2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],
 'prefix': ['2', '3', '4', '5', '6', '7'],
 'compound': ['2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17'],
 'root': ['3', '4', '5', '6', '7'],
 'com': ['2', '3', '4', '5', '6', '7', '8', '10', '17', '20', '22', '28'],
 'doublet': ['2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '20',
  '21'],
 'suf': ['2', '3', '4', '5'],
 'surf': ['2', '3', '4', '5', '6'],
 'confix': ['2', '3', '4'],
 'ko-etym-sino': ['1', '3', '4', '5', '6', '7', '8'],
 'vi-etym-sino': ['1', '3', '5', '7', '8'],
 'blend': ['2', '3', '4'],
 'pre': ['2', '3', '4'],
 'liushu': ['1', '2', '3'],
 'Han compound': ['1', '2', '3', '4'],
 'com+': ['2', '3', '4', '5', '6', '7'],
 'ja-compound': ['1', '2', '3', '4', '5', '6', '7', '8', '10'],
 'dbt': ['2', '3', '4', '5', '6', '10', '11', '12'],
 'ar-root': ['1', '4'],
 'ko-l': ['1', '4'],
 'ko-etym-Sino': ['1', '2', '3', '4', '5', '6', '7', '8'],
 'HE root': ['1', '2'],
 'taxfmt': ['1', '3'],
 'back-form': ['2', '3'],
 'sense': ['1', '2', '3'],
 'obor': ['3', '4', '5'],
 'l-self': ['2', '4'],
 'ja-etym-renyokei': ['1', '2'],
 'io-bor': ['1', '2', '3', '4', '6', '8'],
 'q': ['1', '2'],
 'named-after/list': ['1', '2', '3', '4'],
 'univerbation': ['2', '3', '4', '5'],
 'pseudo-loan': ['3', '4', '5', '6', '7'],
 'rendaku2': ['1', '2', '3'],
 'infix': ['2', '3'],
 'qualifier': ['1', '2'],
 'translit': ['3', '4'],
 'nv-link-to-root': ['1', '2'],
 'cognate': ['2', '3'],
 'nv-prefixes': ['1', '4', '6', '7'],
 'syc-root-entry': ['1', '4'],
 'univ': ['2', '3', '4', '5'],
 'psm': ['3', '5'],
 'sa-root': ['1', '2'],
 'borrowed': ['3', '5'],
 'ja-l': ['1', '3'],
 'as-verb set': ['1', '2'],
 'abbrev': ['2', '4'],
 'com-ja': ['1', '5', '6', '7', '8', '11', '12'],
 'zh-etym-short': ['1', '2', '3', '4', '5', '6', '7', '8', '9'],
 'wasei eigo': ['1', '2', '3'],
 'con': ['2', '3', '4'],
 'th-l': ['1', '2', '3'],
 'surface analysis': ['2', '3', '4', '5', '6'],
 'denominal verb': ['2', '3'],
 'vi-l': ['1', '2', '3'],
 'as-verb-c': ['1', '2'],
 'pt-etym-mente': ['1', '2'],
 'ja-daiyouji': ['1', '2'],
 'll': ['2', '3'],
 'participle of': ['2', '3', '5', '6'],
 'zh-wp': ['1', '8'],
 'hanja-sinjeung': ['1', '2'],
 'hi-verb set': ['1', '2'],
 'iz2': ['2', '3', '4'],
 'he-m': ['1', '3'],
 'ja-com': ['1', '2', '3', '4', '5', '6'],
 'clipping of': ['2', '4'],
 'transliteration': ['3', '5'],
 'elements': ['2', '3', '4', '5', '6'],
 'vi-etym-redup': ['1', '2'],
 'lbor+': ['3', '4', '5'],
 'ryu-kanjitab': ['1', '2'],
 'glink': ['1', '2'],
 'mr-verb set': ['1', '3'],
 'word': ['3', '4'],
 'sa-af': ['2', '3', '4'],
 'ko-sino': ['1', '3', '5', '6'],
 'nom': ['2', '4'],
 'piecewise doublet': ['2', '3'],
 'he-root-link': ['1', '2', '3', '4'],
 'caps': ['1', '3'],
 'he-root': ['1', '2', '3', '4'],
 'see': ['2', '4'],
 't2i-Egyd': ['1', '2', '8'],
 'vi-link': ['1', '3'],
 'ja-ryk': ['1', '2'],
 'diminutive of': ['2', '4'],
 'backformation': ['2', '3'],
 'hi-derform': ['1', '2'],
 'desc': ['2', '4'],
 'C.': ['1', '2'],
 'syncopic form': ['2', '4'],
 'ko-compound-verb': ['1', '3'],
 'waei': ['1', '2'],
 'ja-glossary': ['1', '2'],
 'contraction of': ['2', '4'],
 'is-mms': ['1', '2', '3'],
 'zh-etym-triple': ['1', '2'],
 'ja-rendaku2': ['1', '2', '3'],
 'cardinalbox': ['2', '3', '4', '5', '6'],
 'alter': ['2', '4', '5', '6'],
 'pcp-cmp': ['2', '3', '4'],
 'nv-root': ['1', '2'],
 'ko-etym-verbal-suffix': ['1', '3'],
 'km-redup': ['1', '3']}

In [70]:
word_success_rates['adverbial accusative']

{'nocap': {'total': 18, 'success': 18, 'nonlatin': 0, 'unique': 2},
 '2': {'total': 87, 'success': 14, 'nonlatin': 81, 'unique': 82},
 'gloss': {'total': 11, 'success': 7, 'nonlatin': 0, 'unique': 10},
 '3': {'total': 5, 'success': 3, 'nonlatin': 5, 'unique': 5},
 '4': {'total': 20, 'success': 11, 'nonlatin': 0, 'unique': 19},
 't': {'total': 24, 'success': 20, 'nonlatin': 0, 'unique': 24},
 'tr': {'total': 4, 'success': 3, 'nonlatin': 4, 'unique': 4},
 'nocat': {'total': 1, 'success': 1, 'nonlatin': 0, 'unique': 1}}

In [72]:
collated_templates['cardinalbox']

[{'1': 'ja', '2': '9', '3': '10', '4': '11', '5': '九', '6': '十一'},
 {'1': 'ja', '2': '9', '3': '10', '4': '11', '5': '九', '6': '十一'},
 {'1': 'ja', '2': '9', '3': '10', '4': '11', '5': '九', '6': '十一'},
 {'1': 'vi',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': 'hai',
  '6': 'bốn',
  'ord': 'thứ ba'},
 {'1': 'kbd',
  '2': '7',
  '3': '8',
  '4': '9',
  '5': 'блы',
  '6': 'бгъу',
  'ord': ''},
 {'1': 'zom', '2': '1', '3': '2', '4': '3', '5': 'khet', '6': 'thum'},
 {'1': 'bi', '2': '2', '3': '3', '4': '4', '5': 'tu', '6': 'fo'},
 {'1': 'lou', '2': '5', '3': '6', '4': '7', '5': 'sink', '6': 'sèt'},
 {'1': 'id', '2': '3', '3': '4', '4': '5', '5': 'tiga', '6': 'lima'},
 {'1': 'tkl', '2': '5', '3': '6', '4': '7', '5': 'lima', '6': 'fitu'},
 {'1': 'tkl', '2': '1', '3': '2', '4': '3', '5': 'tahi', '6': 'tolu'},
 {'1': 'tkl', '2': '4', '3': '5', '4': '6', '5': 'fā', '6': 'ono'},
 {'1': 'ga',
  '2': '5',
  '3': '6',
  '4': '7',
  '5': 'cúig',
  '6': 'seacht',
  'ord': 'séú',
  'opt': 'Personal',
  'optx': 'seisear'},
 {'1': 'rap',
  '2': '1',
  '3': '2',
  '4': '3',
  '5': 'tahi',
  '6': 'toru',
  'opt': 'Compound form',
  'optx': 'piti'},
 {'1': 'ga',
  '2': '0',
  '3': '1',
  '4': '2',
  '5': 'náid',
  '6': 'dó',
  'ord': 'céad, aonú',
  'opt': 'Personal',
  'optx': 'aonar',
  'opt2': 'Attributive',
  'opt2x': '(aon)...amháin'},
 {'1': 'ga',
  '2': '0',
  '3': '1',
  '4': '2',
  '5': 'náid',
  '6': 'dó',
  'ord': 'céad, aonú',
  'opt': 'Personal',
  'optx': 'aonar',
  'opt2': 'Attributive',
  'opt2x': '(aon)...amháin'},
 {'1': 'mww',
  '2': '5',
  '3': '6',
  '4': '7',
  '5': 'tsib',
  '6': 'xya',
  'ord': ''},
 {'1': 'ms',
  'sc': 'Arab',
  '2': '٠',
  '3': '١',
  '4': '٢',
  '5': 'کوسوڠ',
  '6': 'دوا'},
 {'1': 'tkl', '2': '7', '3': '8', '4': '9', '5': 'fitu', '6': 'iva'},
 {'1': 'ota',
  'tr': 'altı',
  '2': '5',
  '3': '6',
  '4': '7',
  '5': 'بش',
  '6': 'یدی',
  'ord': 'آلتنجی',
  'ordtr': 'altıncı',
  'dis': 'آلتیشر',
  'distr': 'altışar'},
 {'1': 'lld',
  '2': '8',
  '3': '9',
  '4': '10',
  '5': 'ot',
  '6': 'diesc',
  'ord': 'nono'},
 {'1': 'lld',
  '2': '8',
  '3': '9',
  '4': '10',
  '5': 'ot',
  '6': 'diesc',
  'ord': 'nono'},
 {'1': 'mg', '2': '10³', '3': '10⁴', '4': '', '5': 'arivo', '6': ''},
 {'1': 'vi',
  '2': '8',
  '3': '9',
  '4': '10',
  '5': 'tám',
  '6': 'mười',
  'ord': 'thứ chín'},
 {'1': 'pi',
  '2': '6',
  '3': '7',
  '4': '8',
  '5': 'cha',
  '6': 'aṭṭha',
  'ord': 'sattama'},
 {'1': 'ms', '2': '٠', '3': '١', '4': '٢', '5': 'کوسوڠ', '6': 'دوا'},
 {'1': 'ms',
  '2': '10³',
  '3': '10⁴',
  '4': '10⁵',
  '5': 'ريبو',
  '6': 'راتوس ريبو'},
 {'1': 'ja', '2': '9', '3': '10', '4': '11', '5': 'ナイン', '6': 'イレブン'},
 {'1': 'ja', '2': '0', '3': '1', '4': '2', '5': 'ゼロ', '6': 'ツー'},
 {'1': 'mww',
  '2': '3',
  '3': '4',
  '4': '5',
  '5': 'peb',
  '6': 'tsib',
  'ord': ''},
 {'1': 'lo', '2': '', '3': '໐', '4': '໑', '5': '', '6': 'ໜຶ່ງ', 'ord': ''},
 {'1': 'lo', '2': '', '3': '໐', '4': '໑', '5': '', '6': 'ໜຶ່ງ', 'ord': ''},
 {'1': 'urj-fin-pro',
  '2': '',
  '3': '1000',
  '4': '',
  '5': '',
  '6': '',
  'ord': '*tuhandënci'},
 {'1': 'khb', '2': '᧓', '3': '᧔', '4': '᧕', '5': 'ᦉᦱᧄ', '6': 'ᦠᦱᧉ', 'ord': ''},
 {'1': 'shn',
  '2': '႐',
  '3': '႑',
  '4': '႒',
  '5': 'သူၼ်',
  '6': 'သွင်',
  'ord': 'တီႈၼိုင်ႈ'},
 {'1': 'sco', '2': '7', '3': '8', '4': '9', '5': 'seiven', '6': 'nine'},
 {'1': 'khb', '2': '', '3': '᧐', '4': '᧑', '5': '', '6': 'ᦓᦹᧂᧈ'},
 {'1': 'khb', '2': '', '3': '᧐', '4': '᧑', '5': '', '6': 'ᦓᦹᧂᧈ'},
 {'1': 'juc', '2': '9', '3': '10', '4': '11', '5': 'ujewun'},
 {'1': 'yol',
  '2': '19',
  '3': '20',
  '4': '30',
  '5': 'neenteen',
  '6': 'dhirtee'},
 {'1': 'xkz', '2': '༥', '3': '༦', '4': '༧', '5': 'ཡ་ང', '6': 'ནཱི́'},
 {'1': 'yha', '2': '7', '3': '8', '4': '9', '5': 'ðɦu³³', '6': 'dɦa³³'}]

In [ ]:
collated_templates['acronym']

In [57]:
nonlexical

{'IPA',
 'IPAchar-lite',
 'IPAfont',
 'acronym',
 'adverbial accusative',
 'aii-root',
 'ca-verb-obj',
 'cat',
 'categorize',
 'chess diagram/alt',
 'circa',
 'circa2',
 'coin',
 'coinage',
 'coined',
 'collapse',
 'commonscat',
 'defdate',
 'dercat',
 'es-verb-obj',
 'etydate',
 'etydate/l2',
 'etydate/the',
 'gl',
 'gloss',
 'hanja-dongguk',
 'hanja-hunmong',
 'ic',
 'initialism',
 'it-verb-obj',
 'lang',
 'lit',
 'lw',
 'm-g',
 'named-after',
 'nb...',
 'no deprecated lang param usage',
 'nowrap',
 'nv-link-to-stem',
 'pedia',
 'progreso',
 'ref',
 'refn',
 'ruby',
 'small',
 'topics',
 'uncertain',
 'vern',
 'wp',
 'xlit',
 'zh-ref'}

### Exceptions:

These templates do have their first non-lang key as a word, but we do not detect it:
- acronym (maybe)
- adverbial accusative
- initialism
- cardinalbox: all not words

In [76]:
max([int(k) for k in predicted_word_keys['m']])

2

In [96]:
# these templates take in multiple words
multilexical = {k: v for k, v in predicted_word_keys.items() if len(v) > 1}

# these templates take in arbitrarily many number of words
n_lexical = set()
for tname, keys in predicted_word_keys.items():
    if not keys:
        continue
    try:
        if max([int(k) for k in keys], default=0) >= 6: # if we have a key greater than '6', then it's probably an affix or smth
            n_lexical.add(tname)
        elif '5' in keys and all(key in keys for key in word_success_rates[tname]):
            # all numerical keys from 2-5 are indeed successful
            n_lexical.add(tname)
    except Exception as e:
        print(tname, keys)
        raise e
    

# exceptions
n_lexical.add('Han compound')
n_lexical.add('suf')
n_lexical.add('blend')
n_lexical.add('pre')
n_lexical.remove('cardinalbox')
n_lexical.remove('vi-etym-sino')
n_lexical.remove('t2i-Egyd')

In [95]:
n_lexical

{'Han compound',
 'af',
 'affix',
 'alter',
 'blend',
 'com',
 'com+',
 'com-ja',
 'compound',
 'dbt',
 'doublet',
 'elements',
 'io-bor',
 'ja-com',
 'ja-compound',
 'ko-etym-Sino',
 'ko-etym-sino',
 'ko-sino',
 'nv-prefixes',
 'participle of',
 'pre',
 'prefix',
 'pseudo-loan',
 'root',
 'suf',
 'suffix',
 'surf',
 'surface analysis',
 't2i-Egyd',
 'zh-etym-short',
 'zh-wp'}

In [92]:
predicted_word_keys['blend']

['2', '3', '4']

In [93]:
word_success_rates['blend']

{'2': {'total': 6040, 'success': 5734, 'nonlatin': 622, 'unique': 4173},
 't1': {'total': 653, 'success': 445, 'nonlatin': 19, 'unique': 530},
 '3': {'total': 6023, 'success': 5753, 'nonlatin': 635, 'unique': 4169},
 't2': {'total': 624, 'success': 439, 'nonlatin': 3, 'unique': 524},
 '4': {'total': 174, 'success': 137, 'nonlatin': 79, 'unique': 139},
 'nocap': {'total': 568, 'success': 568, 'nonlatin': 0, 'unique': 6},
 'nocat': {'total': 74, 'success': 74, 'nonlatin': 0, 'unique': 2},
 'tr1': {'total': 156, 'success': 94, 'nonlatin': 63, 'unique': 137},
 'tr2': {'total': 160, 'success': 109, 'nonlatin': 71, 'unique': 142},
 'alt1': {'total': 99, 'success': 20, 'nonlatin': 21, 'unique': 86},
 'alt2': {'total': 75, 'success': 24, 'nonlatin': 23, 'unique': 66},
 'notext': {'total': 52, 'success': 52, 'nonlatin': 0, 'unique': 2},
 'gloss1': {'total': 79, 'success': 46, 'nonlatin': 3, 'unique': 65},
 'gloss2': {'total': 59, 'success': 37, 'nonlatin': 0, 'unique': 55},
 '5': {'total': 33, 'success': 22, 'nonlatin': 23, 'unique': 27},
 'sort': {'total': 37, 'success': 4, 'nonlatin': 37, 'unique': 35},
 'pos1': {'total': 29, 'success': 6, 'nonlatin': 7, 'unique': 25},
 'pos2': {'total': 35, 'success': 9, 'nonlatin': 4, 'unique': 26},
 'alt3': {'total': 4, 'success': 3, 'nonlatin': 1, 'unique': 4},
 'gloss3': {'total': 3, 'success': 1, 'nonlatin': 0, 'unique': 3},
 't3': {'total': 87, 'success': 66, 'nonlatin': 0, 'unique': 57},
 'sc': {'total': 3, 'success': 1, 'nonlatin': 0, 'unique': 2},
 'lit': {'total': 60, 'success': 2, 'nonlatin': 18, 'unique': 56},
 'tr3': {'total': 11, 'success': 7, 'nonlatin': 3, 'unique': 10},
 'id2': {'total': 2, 'success': 2, 'nonlatin': 0, 'unique': 2},
 't4': {'total': 23, 'success': 11, 'nonlatin': 0, 'unique': 19},
 'lit2': {'total': 2, 'success': 2, 'nonlatin': 0, 'unique': 2},
 'qq1': {'total': 6, 'success': 4, 'nonlatin': 0, 'unique': 3},
 'id1': {'total': 6, 'success': 2, 'nonlatin': 0, 'unique': 3},
 'g2': {'total': 1, 'success': 1, 'nonlatin': 0, 'unique': 1},
 '6': {'total': 10, 'success': 6, 'nonlatin': 8, 'unique': 6},
 'tr4': {'total': 4, 'success': 2, 'nonlatin': 0, 'unique': 3},
 't5': {'total': 8, 'success': 6, 'nonlatin': 0, 'unique': 5},
 'tr5': {'total': 2, 'success': 2, 'nonlatin': 0, 'unique': 1},
 '7': {'total': 3, 'success': 2, 'nonlatin': 3, 'unique': 2},
 't6': {'total': 3, 'success': 0, 'nonlatin': 0, 'unique': 2},
 'lit1': {'total': 1, 'success': 0, 'nonlatin': 1, 'unique': 1},
 'pos3': {'total': 1, 'success': 0, 'nonlatin': 0, 'unique': 1},
 'qq2': {'total': 1, 'success': 1, 'nonlatin': 0, 'unique': 1}}

Is correct:
- confix

In [97]:
high_fliers = {k: v for k, v in word_success_rates.items() if '7' in v}

In [ ]:
# for k, v in high_fliers.items():
#     print(k)
# it seems that we do get most of the arbitrarily-many templates

af
affix
prefix
compound
root
com
doublet
ko-etym-sino
vi-etym-sino
blend
com+
ja-compound
dbt
ko-etym-Sino
io-bor
pseudo-loan
nv-prefixes
com-ja
zh-etym-short
zh-wp
t2i-Egyd